name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake .. -G"Visual Studio 15 2017" -DM2O_SERVER=1 -DM2O_CLIENT=1 -DM2O_CEF=1
    - name: build
      run: cmake --build build --config MinSizeRel
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
